FROM node:20-alpine AS base

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./
RUN npm ci --omit=dev

COPY releases/0.9/Bridge ./releases/0.9/Bridge

WORKDIR /app/releases/0.9/Bridge

EXPOSE 3000

CMD ["node", "src/server.js"]
