module.exports = {
  moduleRegistry: require('./module-registry'),
  featureFlags: require('./feature-flags'),
  events: require('./events'),
  runtime: require('./runtime'),
  tenant: require('./tenant'),
  organisation: require('./organisation'),
  identity: require('./identity'),
  auth: require('./auth'),
  rbac: require('./rbac'),
  context: require('../../../src/enterprise/context'),
  audit: require('../../../src/enterprise/audit'),
  workflow: require('../../../src/enterprise/workflow'),
  transactions: require('../../../src/enterprise/transactions'),
  domain: require('../../../src/enterprise/domain'),
  application: require('../../../src/enterprise/application'),
  api: require('../../../src/enterprise/api'),
  policy: require('../../../src/enterprise/policy'),
  cqrs: require('../../../src/enterprise/cqrs'),
  resilience: require('../../../src/enterprise/resilience'),
};
