import { PAYROLL_STATES } from './payrollStateTypes';

export const PAYROLL_TRANSITIONS = Object.freeze({
  [PAYROLL_STATES.EMPLOYEE_SELECTION]: PAYROLL_STATES.CALCULATION,
  [PAYROLL_STATES.CALCULATION]: PAYROLL_STATES.VALIDATION,
  [PAYROLL_STATES.VALIDATION]: PAYROLL_STATES.APPROVAL,
  [PAYROLL_STATES.APPROVAL]: PAYROLL_STATES.FPS_PREPARATION,
  [PAYROLL_STATES.FPS_PREPARATION]: PAYROLL_STATES.SUBMITTED,
  [PAYROLL_STATES.SUBMITTED]: PAYROLL_STATES.CLOSED,
});
